/** Page-specific SEO keywords — Salik Groups & Co always listed first per page. */
export const solutionSeoKeywords = [
  "best electronic services in pakistan",
  "best electronic products in pakistan",
  "best products of electronics in pakistan",
  "best solar panel service in pakistan",
  "solar panel salikgroups",
  "inverters salikgroups",
  "Salik Groups & Co solutions",
] as const;

export const serviceSeoKeywords: Record<string, readonly string[]> = {
  "solar-energy": [
    "Salik Groups & Co solar",
    "best solar panel service in pakistan",
    "solar panel salikgroups",
    "inverters salikgroups",
    "Salik Groups & Co solar energy",
    "commercial solar Pakistan",
    "solar panel installation Lahore",
    "hybrid solar system Pakistan",
    "grid-tied solar Lahore",
    "industrial solar energy",
    "government solar project Pakistan",
    "net metering solar Pakistan",
    "solar inverter supply Lahore",
    "110 KW solar installation",
    "125 KW solar Pakistan",
    "solar EPC contractor Pakistan",
  ],
  "cctv-surveillance": [
    "Salik Groups & Co CCTV",
    "Salik Groups & Co surveillance",
    "CCTV installation Pakistan",
    "IP camera installation Lahore",
    "Safe City CCTV Pakistan",
    "NVR DVR setup Lahore",
    "centralized monitoring system",
    "structured cabling CCTV",
    "security camera supplier Pakistan",
    "commercial CCTV Lahore",
    "government surveillance project",
    "video surveillance integrator",
  ],
  "telephone-exchange": [
    "Salik Groups & Co telephone exchange",
    "PBX installation Pakistan",
    "IP telephony Lahore",
    "office telephone system Pakistan",
    "VoIP solutions Lahore",
    "enterprise phone system",
    "analog digital exchange Pakistan",
    "call routing system Lahore",
  ],
  "electric-fencing": [
    "Salik Groups & Co electric fence",
    "electric fencing Pakistan",
    "perimeter security fence Lahore",
    "high security electric fence",
    "industrial perimeter protection",
    "electric fence installation Pakistan",
    "boundary security systems",
    "energizer fence supplier Lahore",
  ],
  "generators": [
    "Salik Groups & Co generators",
    "generator supply Pakistan",
    "diesel generator Lahore",
    "industrial generator installation",
    "backup power Pakistan",
    "generator maintenance Lahore",
    "commercial generator supplier",
    "standby power systems Pakistan",
  ],
  "video-intercom": [
    "Salik Groups & Co video intercom",
    "video door phone Pakistan",
    "IP intercom system Lahore",
    "apartment intercom Pakistan",
    "building access intercom",
    "video intercom installation Lahore",
    "multi-tenant intercom system",
  ],
  "attendance-machines": [
    "Salik Groups & Co attendance machine",
    "biometric attendance Pakistan",
    "fingerprint scanner Lahore",
    "HR attendance system Pakistan",
    "time attendance machine supplier",
    "face recognition attendance Lahore",
    "employee attendance solution Pakistan",
  ],
  "enterprise-networking": [
    "Salik Groups & Co networking",
    "enterprise networking Pakistan",
    "structured cabling Lahore",
    "fiber optic installation Pakistan",
    "LAN WAN setup Lahore",
    "network infrastructure Pakistan",
    "Cisco networking Lahore",
    "data centre cabling Pakistan",
    "switch router installation",
  ],
  "it-solutions": [
    "Salik Groups & Co IT solutions",
    "IT services Lahore",
    "managed IT Pakistan",
    "server installation Lahore",
    "IT infrastructure Pakistan",
    "enterprise IT support Lahore",
    "computer networking services",
    "IT consultancy Pakistan",
  ],
  "repairing-centre": [
    "Salik Groups & Co repair centre",
    "electronics repair Lahore",
    "CCTV repair Pakistan",
    "generator repair Lahore",
    "solar inverter repair Pakistan",
    "security equipment repair",
    "technical repair services Lahore",
    "after sales support Pakistan",
  ],
};

export const projectSeoKeywords: Record<string, readonly string[]> = {
  "safe-city": [
    "Salik Groups & Co Safe City",
    "Safe City Sialkot",
    "Safe City Sheikhupura",
    "400 CCTV cameras Pakistan",
    "government Safe City project",
    "Salik Groups & Co surveillance",
    "district surveillance Pakistan",
    "centralized monitoring Safe City",
  ],
  "video-wall": [
    "Salik Groups & Co video wall",
    "LED video wall Pakistan",
    "control room display Lahore",
    "command centre video wall",
    "large format display Pakistan",
    "monitoring wall installation",
  ],
  "electric-fence": [
    "Salik Groups & Co electric fence project",
    "perimeter electric fence Pakistan",
    "high security boundary fence",
    "industrial fence installation Lahore",
    "Salik Groups & Co fencing",
  ],
  "uvss": [
    "Salik Groups & Co UVSS",
    "under vehicle surveillance Pakistan",
    "UVSS system Lahore",
    "vehicle scanning security",
    "checkpoint UVSS installation",
    "border security UVSS Pakistan",
  ],
  "networking": [
    "Salik Groups & Co networking project",
    "enterprise network deployment Pakistan",
    "structured cabling project Lahore",
    "fiber network installation Pakistan",
    "Salik Groups & Co networking",
  ],
  "solar": [
    "Salik Groups & Co solar project",
    "commercial solar installation Pakistan",
    "110 KW solar Lahore",
    "government solar deployment",
    "Salik Groups & Co solar energy",
    "industrial solar project Pakistan",
  ],
};

export const legalSeoKeywords = {
  privacy: [
    "Salik Groups & Co privacy policy",
    "Salik Group data protection",
    "Salik Groups & Co privacy",
    "website privacy Pakistan",
  ],
  terms: [
    "Salik Groups & Co terms and conditions",
    "Salik Group service terms",
    "Salik Groups & Co terms of use",
    "technical services agreement Pakistan",
  ],
} as const;
